### ISSUE TITLE
kubeconfig parseerror

### ISSUE THREAD

**Issue by rafhuys-klarrio** [joan38/kubernetes-client#177]
My kubeconfig `env` value does not parse to `Option[Map[String, String]]` but to a list of KV tuples where the first key is `name` and the second is `value`.

```
- name: arn:aws:eks:...:cluster/test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: ...
      env:
      - name: AWS_PROFILE
        value: test
```
To make this library work, I need to change my (generated) kubeconfig to 

```
      args: ...
      env:
        AWS_PROFILE: test
```

How do you cope with this? Is there a Circe flag I can use for this to be parsed correctly?
